### ISSUE TITLE
\dv does not work outside of site in multisite installs

### ISSUE THREAD

**Issue by bronzehedwick** [benjifisher/Vim-Plugin-for-Drupal#1]
I was editing a module file in _all/_ and invoking _\dv_ brings up the following error:

``` viml
:!drush vget 'items'
Command variable-get needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                          [error]

The drush command 'vget items' could not be executed.                                                                                                                              [error]

Could not find a Drupal settings.php file at ./sites/default/settings.php.                                                                                                         [error]


shell returned 1
```

**Comment by benjifisher** [comment]
First of all, consider filing a bug report at http://drupal.org/project/issues/vimrc.  There is a suggestion to move development to GitHub, but it has not happened, yet.  Unless I start getting pull requests, I do not think it is going to happen.

Second, how do you want it to work?  How should vim and/or drush know which site to check if you are working in sites/all/modules/ ?  Should it ask after you have typed \dv or should you set a variable or ... ?

Third, I have not tested it, but I think that drush is invoked in vim's working directory, which may be different from the directory of the file you are editing.  Try

:pwd
:cd /sites/all/mysite

and then try \dv.

**Comment by bronzehedwick** [comment]
Closing
